### ISSUE TITLE
Update dbt-core version

### ISSUE THREAD

**Issue by almeidabbm** [lightdash/cli-actions#15]
Current dbt-core version is not compatible with latest protobuf: https://github.com/dbt-labs/dbt-core/issues/9759

Upgrade dbt-core to [v1.7.10](https://github.com/dbt-labs/dbt-core/releases/tag/v1.7.10)

**Comment by owlas** [comment]
This issue was mentioned by a user in slack: https://lightdash.slack.com/archives/C03HJL000MU/p1710504625016519?thread_ts=1710504625.016519&cid=C03HJL000MU
